### ISSUE TITLE
Implement an interface to view subscribed Watchers

### ISSUE THREAD

**Issue by cpave3** [cpave3/nlog-react#2]
# Task

Once subscribe to Watchers, the client start getting packets of data keyed with Watcher IDs. each Watcher should be represented by a tab or other container.
- [ ] Tabs should remain active in the background
- [ ] Background tabs should show a badge when they get data
- [ ] closing a tab should sever the Listener connection for that Watcher and request an unsubscribe at the server
