### ISSUE TITLE
Implement functionality to get socket data about subscribed Watchers

### ISSUE THREAD

**Issue by cpave3** [cpave3/nlog-react#3]
# Task

The webclient should establish a socket connection to the server, and listen for certain messages on this connection
- [ ] On page load, attempt WSS connection
- [ ] on failure, show a `loading` screen
- [ ] on success, show the subscription list from #1
- [ ] Use a middleware to handle socket events
